# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aaron_cs/Documents/OS_Assignment-2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aaron_cs/Documents/OS_Assignment-2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/clion/163/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron_cs/Documents/OS_Assignment-2/CMakeFiles /home/aaron_cs/Documents/OS_Assignment-2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aaron_cs/Documents/OS_Assignment-2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OS_Assignment-2

# Build rule for target.
OS_Assignment-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OS_Assignment-2
.PHONY : OS_Assignment-2

# fast build rule for target.
OS_Assignment-2/fast:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/build
.PHONY : OS_Assignment-2/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/main.c.s
.PHONY : main.c.s

src/args_vector.o: src/args_vector.c.o

.PHONY : src/args_vector.o

# target to build an object file
src/args_vector.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/args_vector.c.o
.PHONY : src/args_vector.c.o

src/args_vector.i: src/args_vector.c.i

.PHONY : src/args_vector.i

# target to preprocess a source file
src/args_vector.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/args_vector.c.i
.PHONY : src/args_vector.c.i

src/args_vector.s: src/args_vector.c.s

.PHONY : src/args_vector.s

# target to generate assembly for a file
src/args_vector.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/args_vector.c.s
.PHONY : src/args_vector.c.s

src/cd.o: src/cd.c.o

.PHONY : src/cd.o

# target to build an object file
src/cd.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/cd.c.o
.PHONY : src/cd.c.o

src/cd.i: src/cd.c.i

.PHONY : src/cd.i

# target to preprocess a source file
src/cd.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/cd.c.i
.PHONY : src/cd.c.i

src/cd.s: src/cd.c.s

.PHONY : src/cd.s

# target to generate assembly for a file
src/cd.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/cd.c.s
.PHONY : src/cd.c.s

src/echo.o: src/echo.c.o

.PHONY : src/echo.o

# target to build an object file
src/echo.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/echo.c.o
.PHONY : src/echo.c.o

src/echo.i: src/echo.c.i

.PHONY : src/echo.i

# target to preprocess a source file
src/echo.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/echo.c.i
.PHONY : src/echo.c.i

src/echo.s: src/echo.c.s

.PHONY : src/echo.s

# target to generate assembly for a file
src/echo.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/echo.c.s
.PHONY : src/echo.c.s

src/history.o: src/history.c.o

.PHONY : src/history.o

# target to build an object file
src/history.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/history.c.o
.PHONY : src/history.c.o

src/history.i: src/history.c.i

.PHONY : src/history.i

# target to preprocess a source file
src/history.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/history.c.i
.PHONY : src/history.c.i

src/history.s: src/history.c.s

.PHONY : src/history.s

# target to generate assembly for a file
src/history.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/history.c.s
.PHONY : src/history.c.s

src/ls.o: src/ls.c.o

.PHONY : src/ls.o

# target to build an object file
src/ls.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/ls.c.o
.PHONY : src/ls.c.o

src/ls.i: src/ls.c.i

.PHONY : src/ls.i

# target to preprocess a source file
src/ls.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/ls.c.i
.PHONY : src/ls.c.i

src/ls.s: src/ls.c.s

.PHONY : src/ls.s

# target to generate assembly for a file
src/ls.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/ls.c.s
.PHONY : src/ls.c.s

src/pinfo.o: src/pinfo.c.o

.PHONY : src/pinfo.o

# target to build an object file
src/pinfo.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/pinfo.c.o
.PHONY : src/pinfo.c.o

src/pinfo.i: src/pinfo.c.i

.PHONY : src/pinfo.i

# target to preprocess a source file
src/pinfo.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/pinfo.c.i
.PHONY : src/pinfo.c.i

src/pinfo.s: src/pinfo.c.s

.PHONY : src/pinfo.s

# target to generate assembly for a file
src/pinfo.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/pinfo.c.s
.PHONY : src/pinfo.c.s

src/prompt.o: src/prompt.c.o

.PHONY : src/prompt.o

# target to build an object file
src/prompt.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/prompt.c.o
.PHONY : src/prompt.c.o

src/prompt.i: src/prompt.c.i

.PHONY : src/prompt.i

# target to preprocess a source file
src/prompt.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/prompt.c.i
.PHONY : src/prompt.c.i

src/prompt.s: src/prompt.c.s

.PHONY : src/prompt.s

# target to generate assembly for a file
src/prompt.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/prompt.c.s
.PHONY : src/prompt.c.s

src/run_bg.o: src/run_bg.c.o

.PHONY : src/run_bg.o

# target to build an object file
src/run_bg.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/run_bg.c.o
.PHONY : src/run_bg.c.o

src/run_bg.i: src/run_bg.c.i

.PHONY : src/run_bg.i

# target to preprocess a source file
src/run_bg.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/run_bg.c.i
.PHONY : src/run_bg.c.i

src/run_bg.s: src/run_bg.c.s

.PHONY : src/run_bg.s

# target to generate assembly for a file
src/run_bg.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/run_bg.c.s
.PHONY : src/run_bg.c.s

src/run_fg.o: src/run_fg.c.o

.PHONY : src/run_fg.o

# target to build an object file
src/run_fg.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/run_fg.c.o
.PHONY : src/run_fg.c.o

src/run_fg.i: src/run_fg.c.i

.PHONY : src/run_fg.i

# target to preprocess a source file
src/run_fg.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/run_fg.c.i
.PHONY : src/run_fg.c.i

src/run_fg.s: src/run_fg.c.s

.PHONY : src/run_fg.s

# target to generate assembly for a file
src/run_fg.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/run_fg.c.s
.PHONY : src/run_fg.c.s

src/track_bg.o: src/track_bg.c.o

.PHONY : src/track_bg.o

# target to build an object file
src/track_bg.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/track_bg.c.o
.PHONY : src/track_bg.c.o

src/track_bg.i: src/track_bg.c.i

.PHONY : src/track_bg.i

# target to preprocess a source file
src/track_bg.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/track_bg.c.i
.PHONY : src/track_bg.c.i

src/track_bg.s: src/track_bg.c.s

.PHONY : src/track_bg.s

# target to generate assembly for a file
src/track_bg.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/src/track_bg.c.s
.PHONY : src/track_bg.c.s

utils/clear_variables.o: utils/clear_variables.c.o

.PHONY : utils/clear_variables.o

# target to build an object file
utils/clear_variables.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/clear_variables.c.o
.PHONY : utils/clear_variables.c.o

utils/clear_variables.i: utils/clear_variables.c.i

.PHONY : utils/clear_variables.i

# target to preprocess a source file
utils/clear_variables.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/clear_variables.c.i
.PHONY : utils/clear_variables.c.i

utils/clear_variables.s: utils/clear_variables.c.s

.PHONY : utils/clear_variables.s

# target to generate assembly for a file
utils/clear_variables.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/clear_variables.c.s
.PHONY : utils/clear_variables.c.s

utils/init.o: utils/init.c.o

.PHONY : utils/init.o

# target to build an object file
utils/init.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/init.c.o
.PHONY : utils/init.c.o

utils/init.i: utils/init.c.i

.PHONY : utils/init.i

# target to preprocess a source file
utils/init.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/init.c.i
.PHONY : utils/init.c.i

utils/init.s: utils/init.c.s

.PHONY : utils/init.s

# target to generate assembly for a file
utils/init.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/init.c.s
.PHONY : utils/init.c.s

utils/pid_name_pair.o: utils/pid_name_pair.c.o

.PHONY : utils/pid_name_pair.o

# target to build an object file
utils/pid_name_pair.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/pid_name_pair.c.o
.PHONY : utils/pid_name_pair.c.o

utils/pid_name_pair.i: utils/pid_name_pair.c.i

.PHONY : utils/pid_name_pair.i

# target to preprocess a source file
utils/pid_name_pair.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/pid_name_pair.c.i
.PHONY : utils/pid_name_pair.c.i

utils/pid_name_pair.s: utils/pid_name_pair.c.s

.PHONY : utils/pid_name_pair.s

# target to generate assembly for a file
utils/pid_name_pair.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/pid_name_pair.c.s
.PHONY : utils/pid_name_pair.c.s

utils/stack.o: utils/stack.c.o

.PHONY : utils/stack.o

# target to build an object file
utils/stack.c.o:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/stack.c.o
.PHONY : utils/stack.c.o

utils/stack.i: utils/stack.c.i

.PHONY : utils/stack.i

# target to preprocess a source file
utils/stack.c.i:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/stack.c.i
.PHONY : utils/stack.c.i

utils/stack.s: utils/stack.c.s

.PHONY : utils/stack.s

# target to generate assembly for a file
utils/stack.c.s:
	$(MAKE) -f CMakeFiles/OS_Assignment-2.dir/build.make CMakeFiles/OS_Assignment-2.dir/utils/stack.c.s
.PHONY : utils/stack.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... OS_Assignment-2"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/args_vector.o"
	@echo "... src/args_vector.i"
	@echo "... src/args_vector.s"
	@echo "... src/cd.o"
	@echo "... src/cd.i"
	@echo "... src/cd.s"
	@echo "... src/echo.o"
	@echo "... src/echo.i"
	@echo "... src/echo.s"
	@echo "... src/history.o"
	@echo "... src/history.i"
	@echo "... src/history.s"
	@echo "... src/ls.o"
	@echo "... src/ls.i"
	@echo "... src/ls.s"
	@echo "... src/pinfo.o"
	@echo "... src/pinfo.i"
	@echo "... src/pinfo.s"
	@echo "... src/prompt.o"
	@echo "... src/prompt.i"
	@echo "... src/prompt.s"
	@echo "... src/run_bg.o"
	@echo "... src/run_bg.i"
	@echo "... src/run_bg.s"
	@echo "... src/run_fg.o"
	@echo "... src/run_fg.i"
	@echo "... src/run_fg.s"
	@echo "... src/track_bg.o"
	@echo "... src/track_bg.i"
	@echo "... src/track_bg.s"
	@echo "... utils/clear_variables.o"
	@echo "... utils/clear_variables.i"
	@echo "... utils/clear_variables.s"
	@echo "... utils/init.o"
	@echo "... utils/init.i"
	@echo "... utils/init.s"
	@echo "... utils/pid_name_pair.o"
	@echo "... utils/pid_name_pair.i"
	@echo "... utils/pid_name_pair.s"
	@echo "... utils/stack.o"
	@echo "... utils/stack.i"
	@echo "... utils/stack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

